### PR TITLE
rerender with auto

### PR DESCRIPTION
**Pull request by ocefpaf**
This will enable Python 3.6 too.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!

**Comment by ocefpaf** [comment]
I usually wait for the CIs to complete :smile: 
But Windows will probably pass too :wink:

**Comment by blink1073** [comment]
Ah, sorry, I usually merge after CicleCI has passed unless something major has changed (as it has in this case).

**Comment by ocefpaf** [comment]
Even if the change it not major it is nice to let the CIs do their job because there are many moving parts to conda-forge and you may miss: a broken CI config, a need to re-render to fix something, missing dependency for a certain platform, etc. Things sometimes changes so fast that is not uncommon to merge something that is all green just to see it fails when running on master!

**Comment by blink1073** [comment]
The issue I have is having to babysit the PR because I get no notification when the builds actually complete.

**Comment by ocefpaf** [comment]
> The issue I have is having to babysit the PR because I get no notification when the builds actually complete.

I get that. I actually [baby sit tons of PRs](https://twitter.com/ocefpaf/status/819539791498903552) everyday :stuck_out_tongue_winking_eye: 

Anyways, the trick is to trust the person submitting the PR to check them and bug you to merge it. Or is my case I have the power to self-merge it :wink:

**Comment by blink1073** [comment]
Fair enough, I'll limit my rogue behavior to my own PRs.  :wink:

**Comment by ocefpaf** [comment]
> Fair enough, I'll limit my rogue behavior to my own PRs.  :wink:

I am not trying to change how you do things, just letting you know what @conda-forge/core recommends as best practices. Not that, when merging before the CI completion, ideally you should babysit the CIs on `master` to ensure the packages will be uploaded.

**Pull request merged**
